compilers:
- compiler:
    spec: gcc@4.8.5
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
- compiler:
    spec: gcc@11.3.0
    paths:
      cc: /spack/apps/gcc/11.3.0/bin/gcc
      cxx: /spack/apps/gcc/11.3.0/bin/g++
      f77: /spack/apps/gcc/11.3.0/bin/gfortran
      fc: /spack/apps/gcc/11.3.0/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
