modules:
  default:
    roots:
      lmod: /spack/2206/apps/lmod
    enable:
      - lmod
    lmod:
      core_compilers:
        - 'gcc@4.8.5'
      hierarchy:
        - 'mpi'
        - 'lapack'
      hash_length: 0
      whitelist:
        - 'gcc'
        - 'aocc'
        - 'intel'
      blacklist:
        - '%gcc@4.8.5'
      all:
        autoload: none
        conflict:
          - '{name}'
        environment:
          set:
            '{name}_ROOT': '{prefix}'
      tmux:
        template: 'tmux_template.lua'
      screen:
        template: 'screen_template.lua'
      stata:
        template: 'stata_template.lua'
