packages:
  all:
    compiler: [gcc@11.3.0]
    target: [x86_64_v3]
    variants: +pic +ipo +shared +nls ~docs ~doc ~man ~debug
    providers:
      blas: [openblas, intel-oneapi-mkl, blis, amdblis]
      lapack: [openblas, intel-oneapi-mkl, libflame, amdlibflame]
      scalapack: [netlib-scalapack, intel-oneapi-mkl, amdscalapack]
      tbb: [intel-oneapi-tbb]
      mkl: [intel-oneapi-mkl]
      fftw-api: [fftw, intel-oneapi-mkl, amdfftw]
      mpi: [openmpi, mvapich2, mpich, intel-oneapi-mpi]
    permissions:
      read: world
      write: user
      group: spack
  strumpack:
    variants: +butterflypack+c_interface~count_flops+cuda+ipo+mpi+openmp+parmetis~rocm~scotch+shared+slate~task_timers+zfp build_type=RelWithDebInfo cuda_arch=none
  zfp:
    variants: ~aligned+c+cuda~fasthash+fortran+ipo+openmp~profile+python+shared~strided~twoway bsws=64 cuda_arch=none
  kokkos:
    variants: ~aggressive_vectorization~compiler_warnings~cuda~cuda_constexpr~cuda_lambda~cuda_ldg_intrinsic~cuda_relocatable_device_code~cuda_uvm~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~explicit_instantiation~hpx~hpx_async_dispatch+hwloc+ipo+memkind+numactl+openmp~openmptarget+pic+profiling~profiling_load_print~pthread~qthread~rocm+serial+shared~sycl~tests~tuning~wrapper std=14
  slate:
    variants: +cuda+ipo+mpi+openmp~rocm+shared cuda_arch=none
  blaspp:
    variants: +cuda+ipo+openmp~rocm+shared cuda_arch=none
  mesa:
    variants: +glx+llvm+opengl~opengles+osmesa~strip
  mesa-glu:
    variants: +osmesa
  mumps:
    variants: +blr_mt+complex+double+float~incfort~int64+metis+mpi+openmp+parmetis~ptscotch~scotch+shared
  nvtop:
    variants: +cuda+ipo cuda_arch=none support=nvidia
  scotch:
    variants: +compression+esmumps~int64+ipo+metis+mpi+shared
  hypre:
    variants: ~complex~cuda~debug+fortran~gptune~int64~internal-superlu~mixedint+mpi+openmp~rocm+shared~superlu-dist~unified-memory
  hmmer:
    variants: +gsl+mpi
  sox:
    variants: +mp3
  amdblis:
    variants: +blas+cblas~ilp64 libs=shared,static threads=openmp
  libflame:
    variants: ~debug+lapack2flame+shared+static threads=pthreads
  blis:
    variants: +blas+cblas libs=shared,static threads=openmp
  suite-sparse:
    variants: ~cuda~graphblas+openmp+pic~tbb
  superlu-mt:
    variants: +blas~int64+openmp+pic~pthread
  libmicrohttpd:
    variants: +https
  binutils:
    variants: +gas+gold+headers+interwork+ld+libiberty+lto+nls+plugins libs=shared,static
  elfutils:
    variants: +bzip2+debuginfod+nls+xz
  graphviz:
    variants: ~doc+expat+ghostscript~gtkplus+gts~java+libgd~pangocairo+poppler~qt~quartz~x
  gmt:
    variants: +blas~docs+ffmpeg+fftw+gdal+ghostscript+glib+graphicsmagick+lapack+pcre
  gdal:
    variants: +armadillo+cfitsio+crypto+cryptopp+curl+expat+geos+gif+grib+hdf4+hdf5~jasper+java+jpeg~kea+libiconv~libkml+liblzma+libtool+libz~mdb+netcdf+odbc~opencl+openjpeg~pcre+pcre2~perl+pg+png+poppler+proj+python+qhull~sosi+sqlite3+xerces+xml2
  poppler:
    variants: +boost+cms+cpp+glib+gobject+iconv+ipo+jpeg+libcurl+openjpeg+png~qt+tiff+zlib
  postgresql:
    variants: ~client_only+gssapi+perl+python+tcl+threadsafe+xml lineedit=readline
  armadillo:
    variants: +hdf5+ipo
  ior:
    variants: +hdf5+ncmpi
  llvm:
    variants: +clang+compiler-rt+cuda+flang+gold+internal_unwind+libcxx~link_llvm_dylib+lld+lldb~llvm_dylib+mlir+omp_as_runtime+omp_debug+omp_tsan+polly+python+split_dwarf+z3 cuda_arch=60 targets=x86 build_type=Release
  netcdf-c:
    variants: +dap+fsync~hdf4+jna+mpi+parallel-netcdf+pic+shared
  parallel-netcdf:
    variants: +burstbuffer+cxx+fortran+pic+shared
  hdf5:
    variants: +cxx+fortran+hl+ipo+java+mpi+shared+szip+threadsafe+tools api=default
  googletest:
    variants: +gmock+ipo+pthreads+shared
  parmetis:
    variants: +gdb~int64+ipo+shared
  metis:
    variants: +gdb~int64~real64+shared
  mvapich2:
    variants: +alloca~cuda~debug+regcache+wrapperrpath ch3_rank_bits=32 fabrics=mrail file_systems=auto process_managers=auto threads=multiple
  mpich:
    variants: ~argobots~cuda+fortran~hcoll+hwloc+hydra+libxml2+pci~rocm+romio+slurm~two_level_namespace~vci+verbs+wrapperrpath datatype-engine=dataloop device=ch4 netmod=ucx pmi=pmi2
  openmpi:
    variants: +atomics~cuda+cxx+cxx_exceptions~gpfs~internal-hwloc~java+legacylaunchers~lustre~memchecker~pmi+romio+rsh+singularity+static+vt+wrapper-rpath fabrics=ucx schedulers=slurm
  ucx:
    variants: ~assertions~backtrace_detail+cma+cuda+dc+debug+dm+examples+gdrcopy~ib_hw_tm~java~knem+logging+mlx5_dv+openmp+optimizations~parameter_checking+pic+rc+rdmacm~rocm+thread_multiple~ucg+ud+verbs~vfs~xpmem cuda_arch=none libs=shared,static opt=3 simd=auto
  hwloc:
    variants: +cairo+cuda~gl+libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared
  gdb:
    variants: +gold+ld+lto+python+quad+source-highlight+tui+xz
  boost:
    variants: +atomic+chrono~clanglibcpp+container+context+contract+coroutine+date_time~debug+exception+fiber+filesystem+graph+graph_parallel+icu+iostreams+json+locale+log+math~mpi+multithreaded+nowide+numpy+pic+program_options+python+random+regex+serialization+shared+signals~singlethreaded+stacktrace+system~taggedlayout+test+thread+timer+type_erasure~versionedlayout+wave context-impl=fcontext cxxstd=11 visibility=hidden
  util-linux:
    variants: +bash
  gnutls:
    variants: +guile+zlib
  guile:
    variants: +readline threads=posix
  bdw-gc:
    variants: +libatomic-ops threads=posix
  lua:
    variants: +pcfile+shared fetcher=curl
  ncurses:
    variants: ~symlinks+termlib abi=6
  gnuplot:
    variants: +X+cairo+gd+libcerf~pbm~qt~wx
  fftw:
    variants: +mpi+openmp+pfft_patches precision=double,float
  sqlite:
    variants: +column_metadata+dynamic_extensions+fts+functions+rtree
  rust:
    variants: +analysis+clippy+rls+rustfmt+src extra_targets=none
  texlive:
    version: [live]
    variants: scheme=full
  python:
    variants: +bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma+nis+optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib
  r:
    variants: +X+external-lapack+memory_profiling+rmath
  libtiff:
    variants: ~jbig+jpeg~jpeg12+lerc+libdeflate~lzma~old-jpeg~pixarlog+webp+zlib+zstd
  libwebp:
    variants: +gif+jpeg+libwebpdecoder+libwebpdemux+libwebpextras+libwebpmux+png~tiff
  zstd:
    variants: +programs
  cairo:
    variants: +X+fc+ft+gobject+pdf+png~svg
  harfbuzz:
    variants: +graphite2
  pango:
    variants: +X
  glib:
    variants: +libmount tracing=systemtap
  gsl:
    variants: +external-cblas
  openblas:
    variants: ~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=openmp
  vim:
    variants: +cscope~gui~lua~perl~python~ruby~x features=huge
  emacs:
    variants: ~X~native+tls toolkit=gtk
  gmake:
    variants: +guile+nls
  libgit2:
    variants: +curl+ipo+ssh https=openssl
  wget:
    variants: +libpsl+pcre+python+zlib ssl=gnutls
  curl:
    variants: +gssapi~ldap+libidn2~librtmp+libssh+libssh2+nghttp2 tls=openssl
  pcre:
    variants: +jit+multibyte+utf
  pcre2:
    variants: +jit+multibyte
  gettext:
    variants: +bzip2+curses+git+libunistring+libxml2+tar+xz
  cuda:
    version: [11.6.2]
  pmix:
    version: [3.2.3]
  gcc:
    buildable: false
    externals:
    - spec: gcc@11.3.0
      prefix: /spack/apps/gcc/11.3.0/
  singularity:
    buildable: false
    version: [3.10.0]
    externals:
    - spec: singularity@3.10.0
      prefix: /usr
  slurm:
    buildable: false
    version: [21-08-8-2]
    externals:
    - spec: slurm@21-08-8-2
      prefix: /usr
