# Variables can be overridden from gitlab when runninging manually
variables:
  JLSE_SCHEDULER_PARAMETERS: "-A Operations -n 1 -t 10 -q arcticus"
  SPACK_REPOSITORY: https://github.com/spack/spack.git
  SPACK_REF: e4s-21.05 
  SPACK_INSTALLATION: /soft/ecp/spack/e4s-21.05
  WORKING_DIR: ANL/JLSE/Arcticus/E4S-21.05
  SPACK_MIRROR: /soft/ecp/mirrors/arcticus-e4s-21.05
  SPACK_DEPLOY_DIR: /soft/ecp/deploy/e4s-21.05
  # These vals are defaults and may be set on a per-run basis
  REMOVE_BUILDCACHE: "False"
  BUILD_E4S: "True"
  DEPLOY_E4S: "True"

stages:
  - generate
  - build
  - deploy

remove_buildcache:
  stage: generate
  tags:
  - shell
  only:
    variables:
      - $REMOVE_BUILDCACHE == "True"
  script:
#FTW: change path or just ignore for now
  - echo "Removing buildcache at ${SPACK_MIRROR} ..."
  - rm -rf ${SPACK_MIRROR}

generate-spack-pipeline:
  stage: generate
  tags:
  - shell
##  only:
##    variables:
##      - $BUILD_E4S == "True"
#    changes:
#      - ${WORKING_DIR}/spack.yaml

  before_script:
  - pwd
#  - git clone ${SPACK_REPOSITORY} -b e4s-21.02
#  - git clone ${SPACK_REPOSITORY} -b ${SPACK_REF}
# using a local copy here because it's faster...
  - git clone ${SPACK_INSTALLATION} spack-clone
  - cd spack-clone  
  - git log  --oneline -1
  - . share/spack/setup-env.sh
  - which spack
  - spack -V
  - echo $SPACK_ROOT
#  - cd $CI_PROJECT_DIR
  - cd ${CI_PROJECT_DIR}/${WORKING_DIR}

  script:
  - hostname  
  - echo $SPACK_ROOT 
#  - cd $CI_PROJECT_DIR  
  - cd ${CI_PROJECT_DIR}/${WORKING_DIR}
  - rm -rf $HOME/.spack
  - spack env activate .
  - spack env st
#  - export SPACK_GNUPGHOME=$HOME/.gnupg
  - export SPACK_GNUPGHOME=$HOME/spack-gnupg
  - spack gpg list
 # - spack config blame config
 # - spack config blame packages
  - rm -f ${SPACK_ROOT}/etc/spack/defaults/mirrors.yaml
  - spack config blame mirrors
  - spack mirror list
  - spack clean -m
  - spack buildcache list -L --allarch
  - spack concretize -f 2>&1 
# remove a spec to force this pipeline stage to run  
#  - ls -l ${SPACK_MIRROR}/build_cache | grep linux-opensuse_leap15-x86_64-gcc-9.3.0-zlib-1.2.11-x7fpcwas5so6hiemegyf4er3sbbmbpz3.spec.yaml
  - rm -f ${SPACK_MIRROR}/build_cache/linux-opensuse_leap15-x86_64-gcc-9.3.0-zlib-1.2.11-x7fpcwas5so6hiemegyf4er3sbbmbpz3.spec.yaml
  - spack buildcache update-index -d ${SPACK_MIRROR}
  - spack ci generate --dependencies --optimize  --output-file ${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml  
##FTW  - cat ${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml  
  after_script:
  - rm -rf $SPACK_ROOT
  artifacts:
    paths:
    - jobs_scratch_dir/pipeline.yml    

build-e4s:
  stage: build
  only:
    variables:
      - $BUILD_E4S == "True"
#    changes:
#      - ${WORKING_DIR}/spack.yaml
  trigger:
    include:
    - artifact: "jobs_scratch_dir/pipeline.yml"
      job: generate-spack-pipeline
    strategy: depend

deploy:
  stage: deploy
  tags: 
  - shell
  only:
    variables:
      - $DEPLOY_E4S == "True"
  script:
#    - mkdir -p /global/common/software/spackecp/e4s-21.02
#    - cd /global/common/software/spackecp/e4s-21.02
    - echo "FTW - cloning spack into ${SPACK_DEPLOY_DIR}"
    - mkdir -p ${SPACK_DEPLOY_DIR}
    - cd ${SPACK_DEPLOY_DIR}
    - rm -rf spack
    - git clone ${SPACK_REPOSITORY} -b ${SPACK_REF}
    - cd spack
    - source share/spack/setup-env.sh
    # copy all site configuration for spack instance 
#    - cp $CI_PROJECT_DIR/site_config/* $SPACK_ROOT/etc/spack
    - cp ${CI_PROJECT_DIR}/${WORKING_DIR}/site_config/* $SPACK_ROOT/etc/spack
    # the other permission is set to 0 before copying. Adding 4 will ensure user can read the file
    - chmod 664 $SPACK_ROOT/etc/spack/*.yaml
    - export SPACK_GNUPGHOME=$HOME/spack-gnupg
    - spack gpg list
#    - export SPACK_GNUPGHOME=$HOME/.gnupg
    - echo "FTW - updating buildcache index for ${SPACK_MIRROR}"
    - spack buildcache update-index -d ${SPACK_MIRROR}
    - find ${SPACK_MIRROR} -name *.spack -exec chmod o+r {} \;
    - find ${SPACK_MIRROR} -name *.spack 
    - chmod o+r ${SPACK_MIRROR}/build_cache/index.json
    - spack buildcache list -L --allarch
#    - spack env create e4s ${CI_PROJECT_DIR}/${WORKING_DIR}/prod/spack.yaml
#    - spack env activate e4s
# FTW: need to actually cd to the dir to activate environment, otherwise spack won't find the included file
    - cd ${CI_PROJECT_DIR}/${WORKING_DIR}/prod
    - spack env activate .
#    - spack gpg trust ${SPACK_MIRROR}/build_cache/_pgp/*.pub
    - spack -d install --cache-only
    - spack module tcl refresh --delete-tree -y
    - spack find

