variables:
  JLSE_SCHEDULER_PARAMETERS: "-A Operations -n 1  -t 10 -q arcticus_debug"
  SPACK_REPO: /soft/spack-dev
  SPACK_REF: e4s-21.05 
  WORKING_DIR: ./ANL/JLSE/Arcticus/E4S-21.05

before_script:
  - echo "before script"
  - hostname

generate_spack_ci:
  stage: build
  artifacts:
    paths:
    - ./ANL/JLSE/Arcticus/E4S-21.05/.spack-ci.yml 
  tags:
  - shell
  script:
  # couple pieces here to debug what we got
  - pwd
  - ls
  # add some code to clone and checkout a specific spack instance
  # instead of stepping on the system install
  - . ${SPACK_REPO}/share/spack/setup-env.sh
  - which spack
  - spack -V
  - spack gpg list
  - cd ${WORKING_DIR}
  - pwd
  - spack env activate . 
  - spack config blame mirrors
  - spack ci generate --output-file ./.spack-ci.yml
  - cat ./.spack-ci.yml
  - printf "end spack CI gnerate stage\n\n"

run_spack_ci:
  stage: test
  trigger:
    include:
    - ./ANL/JLSE/Arcticus/E4S-21.05/.spack-ci.yml 
      job: generate_spack_ci
    strategy: depend


